language: node_js
node_js:
  - 14
install:
  - yarn install
  - yarn startTestDB
  - yarn typeorm migration:run
script:
  - yarn test
env:
  global:
  - URL_MAIL=http://localhost:3333/answers
  - URL=http://localhost:3333/